// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmtblrPK0lBqrVCRC_ZQofd7g7-lDyVrc',
    appId: '1:263080703449:android:15d63aba90cd1cc0f5d5c8',
    messagingSenderId: '263080703449',
    projectId: 'skoob-d5938',
    databaseURL: 'https://skoob-d5938-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skoob-d5938.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJSnLLQSJSnGY2r5CLxO66yV5Y8hsiXOc',
    appId: '1:263080703449:ios:42de63d7bde426d1f5d5c8',
    messagingSenderId: '263080703449',
    projectId: 'skoob-d5938',
    databaseURL: 'https://skoob-d5938-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skoob-d5938.appspot.com',
    androidClientId: '263080703449-7h6qln9mk0fkl7bq6d7fi5577p9hujnf.apps.googleusercontent.com',
    iosClientId: '263080703449-4mu6vvbcg8jmi65ht1592b6up1vor88e.apps.googleusercontent.com',
    iosBundleId: 'com.example.skoob',
  );

}